<?php

return [
    'current' => '<li class="page-item active"><a class="page-link" href="{{url}}">{{text}}</a></li>',
    'number' => '<li class="page-item"><a class="page-link" href="{{url}}">{{text}}</a></li>',
    'first' => '<li class="page-item"><a class="page-link" href="{{url}}"><span data-feather="chevrons-left" class="rui-icon rui-icon-stroke-1_5"></span></a></li>',
    'prevActive' => '<li class="page-item"><a class="page-link" href="{{url}}"><span data-feather="chevron-left" class="rui-icon rui-icon-stroke-1_5"></span></a></li>',
    'prevDisabled' => '<li class="page-item disabled"><a class="page-link" href="{{url}}"><span data-feather="chevron-left" class="rui-icon rui-icon-stroke-1_5"></span></a></li>',
    'nextActive' => '<li class="page-item"><a class="page-link" href="{{url}}"><span data-feather="chevron-right" class="rui-icon rui-icon-stroke-1_5"></a></li>',
    'nextDisabled' => '<li class="page-item disabled"><a class="page-link" href="{{url}}"><span data-feather="chevron-right" class="rui-icon rui-icon-stroke-1_5"></a></li>',
    'last' => '<li class="page-item"><a class="page-link" href="{{url}}"><span data-feather="chevrons-right" class="rui-icon rui-icon-stroke-1_5"></a></li>',
];

//counterRange The template counter() uses when format == range.
//counterPages The template counter() uses when format == pages.
//ellipsis The template used for ellipses generated by numbers().
//sort The template for a sort link with no direction.
//sortAsc The template for a sort link with an ascending direction.
//sortDesc The template for a sort link with a descending direction.
